use_frameworks!

platform :ios, '10.0'

target 'DDYMaxPodLib_Example' do
  pod 'DDYMaxPodLib', :path => '../'

  target 'DDYMaxPodLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
